#ifndef IDISPATCHGISDATA_GLOBAL_H
#define IDISPATCHGISDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IDISPATCHGISDATA_LIBRARY)
#  define IDISPATCHGISDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define IDISPATCHGISDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IDISPATCHGISDATA_GLOBAL_H
