# Rename this file to application-devel.yml and change the properties so that they match your environment.

application:
  key-store:
    location: PATH TO KEYSTORE FILE
    password: changeit
  jwt:
    key-pair:
      alias: idispatch-identity-server
      password: changeit
